version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-openai-bot
    restart: unless-stopped
    volumes:
      - /home/joesiu/Development/discord-openai-bot/config.json:/config.json
      - /home/joesiu/Development/discord-openai-bot/server.json:/server.json
      - /home/joesiu/Development/discord-openai-bot/prompts:/prompts
