// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commandDescriptions: {
		/**
		 * C​l​e​a​r​ ​c​o​n​t​e​x​t
		 */
		clearContext: string
		/**
		 * G​e​t​ ​c​u​r​r​e​n​t​ ​b​o​t
		 */
		getCurrentBot: string
		/**
		 * R​e​l​o​a​d​ ​c​o​n​f​i​g
		 */
		reloadConfig: string
	}
	messages: {
		/**
		 * C​o​n​t​e​x​t​ ​c​l​e​a​r​e​d
		 */
		contextCleared: string
		/**
		 * B​o​t​ ​c​h​a​n​g​e​d​ ​t​o​ ​{​b​o​t​K​e​y​}
		 * @param {unknown} botKey
		 */
		changedBot: RequiredParams<'botKey'>
		/**
		 * C​o​n​f​i​g​ ​r​e​l​o​a​d​e​d
		 */
		configReloaded: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​r​e​s​p​o​n​s​e​,​ ​r​e​t​r​y​i​n​g​.​.​.​ ​{​r​e​t​r​i​e​s​}
		 * @param {unknown} retries
		 */
		queryRetrying: RequiredParams<'retries'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​r​e​s​p​o​n​s​e​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		responseFailed: RequiredParams<'error'>
	}
	buttons: {
		/**
		 * R​e​t​r​y
		 */
		retry: string
	}
	terms: {
		/**
		 * p​r​o​v​i​d​e​r
		 */
		provider: string
		/**
		 * m​o​d​e​l
		 */
		model: string
	}
}

export type TranslationFunctions = {
	commandDescriptions: {
		/**
		 * Clear context
		 */
		clearContext: () => LocalizedString
		/**
		 * Get current bot
		 */
		getCurrentBot: () => LocalizedString
		/**
		 * Reload config
		 */
		reloadConfig: () => LocalizedString
	}
	messages: {
		/**
		 * Context cleared
		 */
		contextCleared: () => LocalizedString
		/**
		 * Bot changed to {botKey}
		 */
		changedBot: (arg: { botKey: unknown }) => LocalizedString
		/**
		 * Config reloaded
		 */
		configReloaded: () => LocalizedString
		/**
		 * Failed to get response, retrying... {retries}
		 */
		queryRetrying: (arg: { retries: unknown }) => LocalizedString
		/**
		 * Failed to get response, please try again {error}
		 */
		responseFailed: (arg: { error: unknown }) => LocalizedString
	}
	buttons: {
		/**
		 * Retry
		 */
		retry: () => LocalizedString
	}
	terms: {
		/**
		 * provider
		 */
		provider: () => LocalizedString
		/**
		 * model
		 */
		model: () => LocalizedString
	}
}

export type Formatters = {}
